gridftp-le:
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp-le
        DOCKER_FILE: ftp/Dockerfile
    tags:
        - docker-image-build

ftp:
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/ftp
        DOCKER_FILE: gridftp-le/Dockerfile
    tags:
        - docker-image-build

