image: docker:latest

stages:
- build

variables:
    CONTAINER_IMAGE: gitlab-registry.cern.ch/fts/gridftp:latest

before_script:
    - docker info
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" gitlab-registry.cern.ch
    
after_script:
    - docker logout gitlab-registry.cern.ch

build:
    stage: build
    script:
      - docker build --pull -t $CONTAINER_IMAGE .
      - docker push $CONTAINER_IMAGE
    tags:
      - docker

