stages:
- build
- tag

ftp:
    stage: build
    only:
      - master
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/ftp:latest
        CONTEXT_DIR: ftp/
    tags:
        - docker-image-build

gridftp:
    stage: build
    only:
      - master
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp:latest
        CONTEXT_DIR: gridftp/
    tags:
        - docker-image-build

gridftp-le:
    stage: build
    only:
      - master
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp-le:latest
        CONTEXT_DIR: gridftp-le/
    tags:
        - docker-image-build

ftp-release:
    stage: tag
    only:
      - tags
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/ready-to-go/ftp:"$CI_BUILD_REF_NAME"
        CONTEXT_DIR: ftp/
    tags:
        - docker-image-build

gridftp-relase:
    stage: tag
    only:
      - tags
    script:
        - ""
    variables:
        TO:  gitlab-registry.cern.ch/ready-to-go/gridftp:"$CI_BUILD_REF_NAME"
        CONTEXT_DIR: gridftp/
    tags:
        - docker-image-build

gridftp-le-relaese:
    stage: tag
    only:
      - tags
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/ready-to-go/gridftp-le:"$CI_BUILD_REF_NAME"
        CONTEXT_DIR: gridftp-le/
    tags:
        - docker-image-build


#tag:
#    stage: tag
#    only:
#        - tags
#    script:
#      - ""
#    variables:
#      TO: $CONTAINER_RELEASE_IMAGE
#      DOCKER_FILE:  packaging/docker/Dockerfile
#    tags:
#        - docker-image-build

#gridftp:
#    script:
#        - ""
#    variables:
#        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp
#        CONTEXT_DIR: gridftp/
#    tags:
#        - docker-image-build

#gridftp-le:
#    script:
#        - ""
#    variables:
#        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp-le
#        CONTEXT_DIR: gridftp-le/
#    tags:
#        - docker-image-build

#ftp:
#    script:
#        - ""
#    variables:
#        TO: gitlab-registry.cern.ch/fts/ready-to-go/ftp
#        CONTEXT_DIR: ftp/
#    tags:
#        - docker-image-build

