image: docker:latest

stages:
- build

before_script:
    - docker info
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" "${CI_REGISTRY}"
    
after_script:
    - docker logout "${CI_REGISTRY}"

build-gridftp:
    stage: build
    script:
      - cd gridftp
      - docker build --pull -t "${CI_REGISTRY_IMAGE}/gridftp" .
      - docker push "${CI_REGISTRY_IMAGE}/gridftp"
    tags:
      - docker

build-ftp:
    stage: build
    script:
        - cd ftp
        - docker build --pull -t "${CI_REGISTRY_IMAGE}/ftp" .
        - docker push "${CI_REGISTRY_IMAGE}/ftp"
    tags:
        - docker

