gridftp:
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp
        CONTEXT_DIR: gridftp/
    tags:
        - docker-image-build

gridftp-le:
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/gridftp-le
        CONTEXT_DIR: gridftp-le/
    tags:
        - docker-image-build

ftp:
    script:
        - ""
    variables:
        TO: gitlab-registry.cern.ch/fts/ready-to-go/ftp
        CONTEXT_DIR: ftp/
    tags:
        - docker-image-build

