gridftp-server:
    image: gitlab-registry.cern.ch/fts/gridftp:latest
    net: "host"
    ports:
        - "0.0.0.0:80:80"
        - "0.0.0.0:2811:2811"
        - "0.0.0.0:50000-50200:50000-50200"
    environment:
        - TESTCERT=--test-cert
        - EMAIL=example@example.com
        - DOMAIN=dmc-build-01.cern.ch
    volumes:
        - /etc/passwd:/etc/passwd
        - /etc/group:/etc/group
        - ./edg-mkgridmap.conf:/etc/edg-mkgridmap.conf
        - ./localgridmap.conf:/etc/localgridmap.conf
        - /srv:/srv

