version: "2"

services:
    ftp-server:
        image: gitlab-registry.cern.ch/ready-to-go/ftp:latest
        privileged: true
        network_mode: "host"
        ports:
            - "0.0.0.0:21:21"
            - "0.0.0.0:50000-50200:50000-50200"
        volumes:
            - /srv:/var/ftp:ro
