version: "2"

services:
    gridftp-server:
        image: gitlab-registry.cern.ch/fts/ready-to-go/gridftp-le:latest
        build:
          context: .
          args:
            - LOCALGRIDMAP
            - CONTAINERUSERS
            - DOMAIN
            - EMAIL
        network_mode: "host"
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:2811:2811"
            - "0.0.0.0:50000-50200:50000-50200"
        environment:
            - TESTCERT
            - EMAIL
            - DOMAIN
        volumes:
            - ./config/edg-mkgridmap.conf:/etc/edg-mkgridmap.conf
            - ./config/gridftp.conf:/etc/gridftp.conf
            - /srv:/srv
